
package com.mycompany.totemmarte.view;

public class FormDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDialog.class.getName());

    /**
     * Creates new form FormDialog
     */
    public FormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        pnlFooter = new javax.swing.JPanel();
        btnEnviar = new javax.swing.JButton();
        pnlCorpo = new javax.swing.JPanel();
        lblPergunta1 = new javax.swing.JLabel();
        cmbSessao = new javax.swing.JComboBox<>();
        lblPergunta2 = new javax.swing.JLabel();
        cmbFxEtaria = new javax.swing.JComboBox<>();
        lblPergunta3 = new javax.swing.JLabel();
        cmbApresentacao = new javax.swing.JComboBox<>();
        lblPergunta4 = new javax.swing.JLabel();
        cmbNota = new javax.swing.JComboBox<>();
        lblPergunta5 = new javax.swing.JLabel();
        scpMotivo = new javax.swing.JScrollPane();
        txaMotivo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(237, 231, 222));

        pnlHeader.setBackground(new java.awt.Color(0, 0, 0));
        pnlHeader.setPreferredSize(new java.awt.Dimension(580, 50));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlFooter.setPreferredSize(new java.awt.Dimension(756, 60));

        btnEnviar.setText("Enviar");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(btnEnviar)
                .addContainerGap(385, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(pnlFooter, java.awt.BorderLayout.PAGE_END);

        pnlCorpo.setLayout(new java.awt.GridLayout(10, 1));

        lblPergunta1.setText("Escolha uma sessão da galeria");
        pnlCorpo.add(lblPergunta1);

        cmbSessao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlCorpo.add(cmbSessao);

        lblPergunta2.setText("Informe a faixa etária");
        pnlCorpo.add(lblPergunta2);

        cmbFxEtaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlCorpo.add(cmbFxEtaria);

        lblPergunta3.setText("Escolha a apresentação favorita");
        pnlCorpo.add(lblPergunta3);

        cmbApresentacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlCorpo.add(cmbApresentacao);

        lblPergunta4.setText("Nota (1 a 5 estrelas)");
        pnlCorpo.add(lblPergunta4);

        cmbNota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlCorpo.add(cmbNota);

        lblPergunta5.setText("Por que gostou?");
        pnlCorpo.add(lblPergunta5);

        txaMotivo.setColumns(20);
        txaMotivo.setRows(5);
        scpMotivo.setViewportView(txaMotivo);

        pnlCorpo.add(scpMotivo);

        getContentPane().add(pnlCorpo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormDialog dialog = new FormDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> cmbApresentacao;
    private javax.swing.JComboBox<String> cmbFxEtaria;
    private javax.swing.JComboBox<String> cmbNota;
    private javax.swing.JComboBox<String> cmbSessao;
    private javax.swing.JLabel lblPergunta1;
    private javax.swing.JLabel lblPergunta2;
    private javax.swing.JLabel lblPergunta3;
    private javax.swing.JLabel lblPergunta4;
    private javax.swing.JLabel lblPergunta5;
    private javax.swing.JPanel pnlCorpo;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JScrollPane scpMotivo;
    private javax.swing.JTextArea txaMotivo;
    // End of variables declaration//GEN-END:variables
}
